name: linting

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!.dockerignore'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.7.5
        poetry_version: 0.12.17
        args: install
    - name: Run flake8
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.7.5
        poetry_version: 0.12.17
        args: run flake8
    - name: Run mypy
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.7.5
        poetry_version: 0.12.17
        args: run mypy --ignore-missing-imports --strict-optional .
