name: linting

on: 
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!.dockerignore'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run flake8
      uses: abatilo/actions-poetry@master
      with:
        args: run flake8
    - name: Run mypy
      uses: abatilo/actions-poetry@master
      with:
        args: run mypy --ignore-missing-imports --strict-optional .
